In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from tensorflow import keras

In [2]:
df = pd.read_csv(r'C:\Users\shaik\Downloads\Irisdataset.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [7]:
species_name = le.classes_
print(species_name)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [8]:
X = df.drop(columns=['Id', 'Species'])
y = df['Species']
X.head(3)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2

In [9]:
print(y[:5])

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int32


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=69)

In [11]:
x_train.shape

(105, 4)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
print(x_train[:1])
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train[:1])

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
57            4.9           2.4            3.3           1.0
[[-1.14630942 -1.44374444 -0.25650655 -0.258263  ]]


In [13]:
y_train = keras.utils.to_categorical(y_train, num_classes=3)
print(y_train[:5])

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [14]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [15]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(x_train.shape[-1], )))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=3, activation='softmax'))

In [16]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1315 (5.14 KB)
Trainable params: 1315 (5.14 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.fit(x_train, y_train, epochs=100, verbose=2)

Epoch 1/100


4/4 - 1s - loss: 1.2358 - accuracy: 0.4095 - 1s/epoch - 296ms/step
Epoch 2/100
4/4 - 0s - loss: 1.1866 - accuracy: 0.4095 - 10ms/epoch - 3ms/step
Epoch 3/100
4/4 - 0s - loss: 1.1379 - accuracy: 0.3524 - 16ms/epoch - 4ms/step
Epoch 4/100
4/4 - 0s - loss: 1.0697 - accuracy: 0.4762 - 18ms/epoch - 4ms/step
Epoch 5/100
4/4 - 0s - loss: 1.0034 - accuracy: 0.4857 - 16ms/epoch - 4ms/step
Epoch 6/100
4/4 - 0s - loss: 0.9565 - accuracy: 0.5714 - 16ms/epoch - 4ms/step
Epoch 7/100
4/4 - 0s - loss: 0.9390 - accuracy: 0.6000 - 16ms/epoch - 4ms/step
Epoch 8/100
4/4 - 0s - loss: 0.8917 - accuracy: 0.6476 - 16ms/epoch - 4ms/step
Epoch 9/100
4/4 - 0s - loss: 0.8286 - accuracy: 0.7524 - 10ms/epoch - 3ms/step
Epoch 10/100
4/4 - 0s - loss: 0.7813 - accuracy: 0.7429 - 12ms/epoch - 3ms/step
Epoch 11/100
4/4 - 0s - loss: 0.7720 - accuracy: 0.7619 - 12ms/epoch - 3ms/step
Epoch 12/100
4/4 - 0s - loss: 0.6920 - accuracy: 0.8190 - 18ms/epoch - 5ms/step
Epoch 13/100
4/4 - 0s - loss: 0.6517 - accuracy

In [18]:
prediction = model.predict(x_test)
print(prediction[:5])

2/2 [==============================] - 0s 4ms/step
[[9.9948275e-01 5.0477020e-04 1.2428605e-05]
 [4.7330959e-03 8.8753253e-01 1.0773434e-01]
 [9.9849081e-01 1.4714017e-03 3.7791746e-05]
 [4.3343382e-05 2.1053642e-02 9.7890306e-01]
 [9.9825329e-01 1.6982048e-03 4.8423695e-05]]


In [19]:
prediction = np.argmax(prediction, axis=-1)
print(prediction[:5])

[0 1 0 2 0]


In [20]:
print(y_test[:5])

4      0
58     1
20     0
114    2
31     0
Name: Species, dtype: int32


In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction))

0.9777777777777777


In [22]:
cm = confusion_matrix(y_test, prediction)
print(cm)

[[16  0  0]
 [ 0 12  0]
 [ 0  1 16]]


In [23]:
# Save the model
model.save('iris_model.h5')

c:\Users\shaik\.conda\envs\tensorflow\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
